export enum IconSets {
  Bootstrap = 'bs',
  Boxicons = 'bx',
  Bytesize = 'by',
  Cssgg = 'gg',
  Emojicc = 'em',
  Eos = 'eo',
  Feather = 'ft',
  Flags = 'fl',
  Fontawesome = 'fa',
  Iconoir = 'in',
  Iconpark = 'ip',
  Lucide = 'lu',
  Material = 'mi',
  Phosphor = 'ph',
  Supertiny = 'st',
  Symbols = 'ms',
  Tabler = 'ti',
}
