export enum IconSets {
  bootstrap = 'bs',
  boxicons = 'bx',
  bytesize = 'by',
  cssgg = 'gg',
  emojicc = 'em',
  eos = 'eo',
  feather = 'ft',
  flags = 'fl',
  fontawesome = 'fa',
  iconoir = 'in',
  iconpark = 'ip',
  lucide = 'lu',
  material = 'mi',
  phosphor = 'ph',
  supertiny = 'st',
  symbols = 'ms',
  tabler = 'ti',
}
